# Generated by Django 5.0 on 2024-01-04 03:57

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('videointro', models.FileField(blank=True, upload_to='')),
                ('thumbnail', models.ImageField(null=True, upload_to='Course/')),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('summary', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple choice', 'Multiple Choice'), ('trueorfalse', 'True, False'), ('fillintheblank', 'Fill in the blank'), ('onechoice', 'One choice answer')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentarySector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('contentfile', models.FileField(blank=True, upload_to='')),
                ('videolecture', models.FileField(blank=True, upload_to='')),
                ('documentary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.documentary')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.question')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('documentarysector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserApp.documentarysector')),
                ('questions', models.ManyToManyField(to='UserApp.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quizz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.quiz'),
        ),
        migrations.CreateModel(
            name='UserDocumentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isfinished', models.BooleanField(default=False)),
                ('perfinished', models.IntegerField(default=0)),
                ('datemodified', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('documentary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.documentary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDocumentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('quiz_score', models.IntegerField(blank=True, default=-1, null=True)),
                ('scorerequirement', models.IntegerField(default=0)),
                ('nquizz', models.IntegerField(default=0)),
                ('datemodified', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('documentarysector', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='UserApp.documentarysector')),
                ('userdocumentary', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='UserApp.userdocumentary')),
            ],
        ),
        migrations.CreateModel(
            name='UserQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.quiz')),
                ('userdocumentsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.userdocumentsection')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.question')),
                ('userquiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.userquiz')),
            ],
        ),
    ]
