# Generated by Django 5.0 on 2024-01-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_quiz_nrepeat_userquiz_numbertaken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='nrepeat',
            field=models.IntegerField(default=-1),
        ),
    ]
