# Generated by Django 5.0 on 2024-01-04 08:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_alter_quiz_nrepeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquiz',
            name='joindate',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='userquiz',
            name='startdate',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='userquiz',
            name='testminiutes',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='userdocumentsection',
            name='documentarysector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.documentarysector'),
        ),
        migrations.AlterField(
            model_name='userdocumentsection',
            name='userdocumentary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.userdocumentary'),
        ),
    ]
