# Generated by Django 5.0 on 2024-01-04 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_userquiz_joindate_userquiz_startdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquiz',
            name='joindate',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='userquiz',
            name='startdate',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
