# Generated by Django 5.0 on 2024-01-04 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_alter_userquiz_joindate_alter_userquiz_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquiz',
            name='joindate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='userquiz',
            name='startdate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
