# Generated by Django 5.0 on 2024-01-05 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_alter_userquiz_joindate_alter_userquiz_startdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdocumentsection',
            name='nquizz',
        ),
        migrations.RemoveField(
            model_name='userquiz',
            name='numbertaken',
        ),
    ]
