# Generated by Django 5.0 on 2024-01-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0008_remove_userdocumentsection_nquizz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquiz',
            name='quizscore',
            field=models.IntegerField(default=0),
        ),
    ]
