# Generated by Django 5.0 on 2024-01-05 07:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0011_alter_userquiz_joindate_alter_userquiz_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquiz',
            name='joindate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userquiz',
            name='startdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
