# Generated by Django 5.0 on 2024-01-05 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0012_alter_userquiz_joindate_alter_userquiz_startdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='tmp_UserQuizQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionindex', models.IntegerField(default=0)),
                ('listquestionanswer', models.ManyToManyField(blank=True, to='UserApp.questionanswer')),
                ('questions', models.ManyToManyField(blank=True, to='UserApp.question')),
                ('userquiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.userquiz')),
            ],
        ),
    ]
