# Generated by Django 5.0 on 2024-01-07 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0013_tmp_userquizquestionanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tmp_userquizquestionanswer',
            name='questions',
        ),
        migrations.CreateModel(
            name='tmp_UQ_QuestionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionindex', models.IntegerField(default=-1)),
                ('UQ_Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.tmp_userquizquestionanswer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.question')),
            ],
        ),
        migrations.AddField(
            model_name='tmp_userquizquestionanswer',
            name='related_questions',
            field=models.ManyToManyField(blank=True, related_name='related_answers', to='UserApp.tmp_uq_questionuser'),
        ),
    ]
