# Generated by Django 5.0 on 2024-01-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0015_userquiz_testdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquiz',
            name='startdate',
        ),
        migrations.AddField(
            model_name='answer',
            name='answerorder',
            field=models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')], default=-1),
        ),
    ]
