# Generated by Django 5.0 on 2024-01-07 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0016_remove_userquiz_startdate_answer_answerorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tmp_userquizquestionanswer',
            name='listquestionanswer',
        ),
        migrations.AddField(
            model_name='tmp_uq_questionuser',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserApp.answer'),
        ),
    ]
