# Generated by Django 5.0 on 2024-01-11 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0019_quiz_scorerequirement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(default='')),
                ('portrait', models.FileField(null=True, upload_to='User/')),
                ('bio', models.TextField(default='')),
                ('href_facebook', models.TextField(default='')),
                ('href_twitter', models.TextField(default='')),
                ('href_blog', models.TextField(default='')),
                ('href_github', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
