# Generated by Django 5.0 on 2024-01-11 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0021_userinfo_phone_alter_userinfo_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='questions',
        ),
    ]
